### ISSUE TITLE
No release, no dmg file

### ISSUE THREAD

**Issue by derhuerst** [robbertkl/ResolutionMenu#2]
I would like to test your software (:

unfortunately, I have neither the skill nor the setup to compile this by my own. according to the readme.md, there is a dmg file for the latest release, but there is no release.

is this repo still active?

**Comment by robbertkl** [comment]
There's no active development (not much to be done actually), but it still works fine. You're right, the DMG seems to be missing, I'll try to take care of it soon.

As for compiling it yourself: if you have Xcode installed, it's pretty plug & play.

**Comment by derhuerst** [comment]
As a web developer, I usually don't come in touch with Xcode. And i try to avoid having a GB application on my computer. :P

thanks for taking care of the DMg :+1:

**Comment by robbertkl** [comment]
Sorry, lost track of this. I've just added pre-compiled versions in the [Releases section](https://github.com/robbertkl/ResolutionMenu/releases). Also fixed support for OS X dark mode in the process.
