### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by iemg** [robbertkl/ResolutionMenu#6]
Hello! Love this handy tool and wonder if it will be ported to Apple Silicon? :)

Best

**Comment by shaodavid** [comment]
Yes, I am also a long-time supporter of this tool.  Would love to see it get updated to work on the new Macs

**Comment by robbertkl** [comment]
Hi! Thanks for creating this issue, I somehow missed the notification back in July.

I've just created a new build with the current code, which baked a universal binary. It seems to work fine on my M1 Max, but haven't been able to test with multiple monitors.

Could you let me know if this works for you? See [the v1.2 release](https://github.com/robbertkl/ResolutionMenu/releases/tag/v1.2). Feel free to reopen or create a new issue if you run into problems.

**Comment by iemg** [comment]
Thank you! :) I will test it with my multi monitor setup the next days but on my MacBook Air M2 it already works like a charm.

**Comment by shaodavid** [comment]
Summary of the v1.2 from my end:
- Works with M1 Macs built-in displays (works on my 16in M1 MBP in HiDPI mode)
- Works with non-HiDPI displays, tested on my Dell 34 Ultrawide
- Issue: Does not work on HiDPI displays, including my: Dell 4K 27in, LG 5K Ultrafine

**Comment by iemg** [comment]
I tested it with a non-HiDPI external display, which yields following strange list of options:
<img width="184" alt="Bildschirm­foto 2023-02-19 um 16 12 37" src="https://user-images.githubusercontent.com/9716564/219956887-8a91a8d0-098c-4d3c-87a0-8a76ea5d7b94.png">

Apart from that resolution change works without problems. I will still reopen that because the menu is cluttered, but it's not a critical bug.
